name: Bluestock Node.js CI/CD

on:
  push:
    branches: [main]  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # Optional: Lint or test here
    # - name: Run lint/test
    #   run: npm run test

    - name: Upload build artifacts (optional frontend dist)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: project-files
        path: |
          .
          !node_modules/
